version: '2'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - app-network
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "8080:80"
    networks:
      - app-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000"
    links:
      - redis:redis
    depends_on:
      - redis
    environment:
      - INSTANCE=node1
      - REDIS_URL=redis://cache
    networks:
      - app-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000"
    links:
      - redis:redis
    depends_on:
      - redis
    environment:
      - INSTANCE=node2
      - REDIS_URL=redis://cache
    networks:
      - app-network

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000"
    links:
      - redis:redis
    depends_on:
      - redis
    environment:
      - INSTANCE=node3
      - REDIS_URL=redis://cache
    networks:
      - app-network

networks:
  app-network:
    driver: bridge